version: '2'
services:
  mongo:
    image: mongo:3.6
    ports:
      - 27017:27017
    volumes:
      - "mongodata:/data/db"
    networks:
      - mongo

  mongo-express:
    image: mongo-express:0.42
    ports:
      - 8081:8081
    depends_on:
      - mongo
    networks:
      - mongo

volumes:
  mongodata:
    driver: local

networks:
  mongo:
    external: false
