version: "3"

services:
  db:
    image: postgres:10.1
    restart: always
    ports:
      - 5432:5432
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: postgrespw

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata:
