---
# DO NOT USE IT for production without change of all credentials!!
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: database
type: Opaque
data:
  # minio-access-key
  MINIO_ACCESS_KEY: bWluaW8tYWNjZXNzLWtleQ==
  # minio-secret-key
  MINIO_SECRET_KEY: bWluaW8tc2VjcmV0LWtleQ==
